### ISSUE TITLE
Patterns Table X-Axis[BUG]

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/observability#1252] opened 2022-11-04 16:10 UTC
**What is the bug?**
Clicking in the patterns table changes the X-axis of the chart to Jan 1 2022, regardless of the selected interval

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by joshuali925** [comment] 2022-11-04 20:44
duplicate of #1249 , the x-axis is beginning of the year because the internal interval value is `year` instead of what is displayed on UI

**Closed by joshuali925** 2022-11-04 20:44 UTC
Labels: bug, untriaged
