### ISSUE TITLE
Support time based indices in PPL

### ISSUE THREAD

**Issue by tgueldner** [opensearch-project/observability#350] opened 2021-12-16 12:33 UTC
The source parameter of PPL accepts an index name. The examples decribed under https://opensearch.org/docs/latest/observability/ppl/index/ and the sample data of Observability Event analytics like `opensearch_dashboards_sample_data_logs` seems to accept only "static" index names.

In our environment we use time based indices like `logs-myserver-YYYY.MM.DD` to take advantage of ISM. I haven't yet found a way to use PPL with these indexes in a generic approach. 

**Feature request**
PPL should be able to address index patterns like `logs-myserver-*` instead of the index directly.

**Comment by penghuo** [comment] 2022-02-08 18:03
PPL supports [wildcard matching](https://github.com/opensearch-project/sql/blob/main/docs/user/ppl/general/identifiers.rst#multiple-indices).

**Comment by penghuo** [comment] 2022-02-11 01:04
sure.

**Comment by penghuo** [comment] 2022-02-11 01:11
It is good to close the issue. 
@brijos I do not have permission to close. Could you help?

**Comment by penghuo** [comment] 2022-02-11 19:15
Test PPL using Rest API, no issue found. @mengweieric Could you help  checking the frontend?
```
###
POST {{baseUrl}}/log-myserver-2022.01/_doc/
Content-Type: application/json

{ "l1": 1, "l2": 2}

###
POST {{baseUrl}}/log-myserver-2022.02/_doc/
Content-Type: application/json

{ "l1": 1, "l2": 3}

###
POST {{baseUrl}}/log-myserver-2022.03/_doc/
Content-Type: application/json

{ "l1": 1, "l2": 4}


###
POST {{baseUrl}}/_plugins/_ppl/
Content-Type: application/json

{
  "query": "source=log-myserver-2022.* | stats count()"
}
```

**Comment by mengweieric** [comment] 2022-03-14 19:42
Hi @tgueldner,

Thanks for providing detailed debugging information. The root cause for this was dashboard-observability 1.2.0 does not support multi indexes/index patterns, therefore when searching, it's unable to get the timestamp. This support has been added in 1.3 release.

**Closed by mengweieric** 2022-03-14 19:42 UTC
Labels: enhancement
