### ISSUE TITLE
[BUG]: UI gets crashed when space is added in Custom label

### ISSUE THREAD

**Issue by pratibhapandey16** [opensearch-project/observability#1025] opened 2022-09-15 10:50 UTC
**What is the bug?**
When user adds space in the Custom label input section(Series section) in Data Config panel, the UI gets crashed.

**How can one reproduce the bug?**
1. Go to Observability/Event Analytics/Explorer page
2. Enter the query in PPL query section and select 'Year to date' option from calendar and click on 'Refresh'
3. Navigate to Visualizations page
4. Select Vertical bar chart from chart dropdown
5. Type a name in Custom label under Series section for Data Config panel(E.g. custom label) 
6. Click on Update chart
7. UI gets crashed.

**What is the expected behavior?**
The UI should load properly.

@anirudha @mengweieric
cc: @abasatwar @spattnaik

**Comment by mengweieric** [comment] 2022-10-10 17:30
Please just handle the it correctly without app crash, but we don't put and validations on custom label, and let the ppl plugin to throw errors. UI just need to capture any PPL query errors and display it in the error notifications under the query bar.

**Comment by ruchika-narang** [comment] 2022-10-14 10:15
Now the app doesn't crash and shows a valid error and as per our discussion on slack this seems to be expected behavior so closing this issue. Thanks

**Closed** 2022-10-14 10:15 UTC
Labels: bug, v2.4.0
